language: node_js
node_js:
  - '0.10'
  - '0.8'
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
install: npm install
script: grunt test
branches:
  only:
    - master
notifications:
  email:
    on_success: never
    on_failure: change
